### ISSUE TITLE
Can you tell me how to install Filestore on Agiletoolkit ? composer does not install it!

### ISSUE THREAD

**Issue by rapgithub** [romaninsh/upload#2]
I am trying to use Filestore in my agiletoolkit and I tried Filestore composer installation and it gives me error it does not install it....

I want to use also upload here but I need also Filestore...

can you please check Filestore and files something is missing for correct installation

thanks

**Comment by DarkSide666** [comment]
See https://github.com/atk4/filestore and https://github.com/atk4/ui/blob/develop/demos/upload.php.

Maybe that could help you.

**Comment by romaninsh** [comment]
closing as too broad.
